// <auto-generated />
using GozbaNaKlikApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GozbaNaKlikApplication.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260119175456_m4")]
    partial class m4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GozbaNaKlikApplication.Models.AdministratorProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("Administrators");

                    b.HasData(
                        new
                        {
                            UserId = 1
                        },
                        new
                        {
                            UserId = 2
                        },
                        new
                        {
                            UserId = 3
                        });
                });

            modelBuilder.Entity("GozbaNaKlikApplication.Models.CourierProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("UserId");

                    b.ToTable("Couriers");
                });

            modelBuilder.Entity("GozbaNaKlikApplication.Models.CustomerProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("GozbaNaKlikApplication.Models.OwnerProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("GozbaNaKlikApplication.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "aleksandarpopov@gmail.com",
                            Name = "Aleksandar",
                            PasswordHash = "admin1",
                            Role = 2,
                            Surname = "Popov",
                            Username = "Admin1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "nikolapopovski@gmail.com",
                            Name = "Nikola",
                            PasswordHash = "admin2",
                            Role = 2,
                            Surname = "Popovski",
                            Username = "Admin2"
                        },
                        new
                        {
                            Id = 3,
                            Email = "petarnikolic@gmail.com",
                            Name = "Petar",
                            PasswordHash = "admin3",
                            Role = 2,
                            Surname = "Nikolic",
                            Username = "Admin3"
                        });
                });

            modelBuilder.Entity("GozbaNaKlikApplication.Models.AdministratorProfile", b =>
                {
                    b.HasOne("GozbaNaKlikApplication.Models.User", "User")
                        .WithOne("AdministratorProfile")
                        .HasForeignKey("GozbaNaKlikApplication.Models.AdministratorProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GozbaNaKlikApplication.Models.CourierProfile", b =>
                {
                    b.HasOne("GozbaNaKlikApplication.Models.User", "User")
                        .WithOne("CourierProfile")
                        .HasForeignKey("GozbaNaKlikApplication.Models.CourierProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GozbaNaKlikApplication.Models.CustomerProfile", b =>
                {
                    b.HasOne("GozbaNaKlikApplication.Models.User", "User")
                        .WithOne("CustomerProfile")
                        .HasForeignKey("GozbaNaKlikApplication.Models.CustomerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GozbaNaKlikApplication.Models.OwnerProfile", b =>
                {
                    b.HasOne("GozbaNaKlikApplication.Models.User", "User")
                        .WithOne("OwnerProfile")
                        .HasForeignKey("GozbaNaKlikApplication.Models.OwnerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GozbaNaKlikApplication.Models.User", b =>
                {
                    b.Navigation("AdministratorProfile");

                    b.Navigation("CourierProfile");

                    b.Navigation("CustomerProfile");

                    b.Navigation("OwnerProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
