// <auto-generated />
using System;
using GozbaNaKlikApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GozbaNaKlikApplication.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260219133856_UpdateAddressModel")]
    partial class UpdateAddressModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AllergenCustomerProfile", b =>
                {
                    b.Property<int>("CustomerAllergensId")
                        .HasColumnType("integer");

                    b.Property<int>("CustomerProfileUserId")
                        .HasColumnType("integer");

                    b.HasKey("CustomerAllergensId", "CustomerProfileUserId");

                    b.HasIndex("CustomerProfileUserId");

                    b.ToTable("CustomerAllergens", (string)null);
                });

            modelBuilder.Entity("AllergenMeal", b =>
                {
                    b.Property<int>("MealAllergensId")
                        .HasColumnType("integer");

                    b.Property<int>("MealId")
                        .HasColumnType("integer");

                    b.HasKey("MealAllergensId", "MealId");

                    b.HasIndex("MealId");

                    b.ToTable("MealAllergens", (string)null);
                });

            modelBuilder.Entity("GozbaNaKlikApplication.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Apartment")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CustomerProfileId")
                        .HasColumnType("integer");

                    b.Property<int?>("Floor")
                        .HasColumnType("integer");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StreetNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerProfileId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("GozbaNaKlikApplication.Models.AdministratorProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("Administrators");

                    b.HasData(
                        new
                        {
                            UserId = 1
                        },
                        new
                        {
                            UserId = 2
                        },
                        new
                        {
                            UserId = 3
                        });
                });

            modelBuilder.Entity("GozbaNaKlikApplication.Models.Allergen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Allergens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Gluten"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Lactose"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Peanuts"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Soy"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Eggs"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Fish"
                        });
                });

            modelBuilder.Entity("GozbaNaKlikApplication.Models.CourierProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("UserId");

                    b.ToTable("Couriers");
                });

            modelBuilder.Entity("GozbaNaKlikApplication.Models.CustomerProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("GozbaNaKlikApplication.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("GozbaNaKlikApplication.Models.OwnerProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("GozbaNaKlikApplication.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("GozbaNaKlikApplication.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "aleksandarpopov@gmail.com",
                            Name = "Aleksandar",
                            PasswordHash = "$2a$11$Z/QwBhXbDM1i8YdaUyJCa.ySiEr9Pk7RulGvrN2WdyMauTeEcvdNy",
                            Role = 2,
                            Surname = "Popov",
                            Username = "Admin1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "nikolapopovski@gmail.com",
                            Name = "Nikola",
                            PasswordHash = "$2a$11$Z/QwBhXbDM1i8YdaUyJCa.ySiEr9Pk7RulGvrN2WdyMauTeEcvdNy",
                            Role = 2,
                            Surname = "Popovski",
                            Username = "Admin2"
                        },
                        new
                        {
                            Id = 3,
                            Email = "petarnikolic@gmail.com",
                            Name = "Petar",
                            PasswordHash = "$2a$11$Z/QwBhXbDM1i8YdaUyJCa.ySiEr9Pk7RulGvrN2WdyMauTeEcvdNy",
                            Role = 2,
                            Surname = "Nikolic",
                            Username = "Admin3"
                        });
                });

            modelBuilder.Entity("AllergenCustomerProfile", b =>
                {
                    b.HasOne("GozbaNaKlikApplication.Models.Allergen", null)
                        .WithMany()
                        .HasForeignKey("CustomerAllergensId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GozbaNaKlikApplication.Models.CustomerProfile", null)
                        .WithMany()
                        .HasForeignKey("CustomerProfileUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AllergenMeal", b =>
                {
                    b.HasOne("GozbaNaKlikApplication.Models.Allergen", null)
                        .WithMany()
                        .HasForeignKey("MealAllergensId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GozbaNaKlikApplication.Models.Meal", null)
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GozbaNaKlikApplication.Models.Address", b =>
                {
                    b.HasOne("GozbaNaKlikApplication.Models.CustomerProfile", "CustomerProfile")
                        .WithMany("CustomerAddresses")
                        .HasForeignKey("CustomerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerProfile");
                });

            modelBuilder.Entity("GozbaNaKlikApplication.Models.AdministratorProfile", b =>
                {
                    b.HasOne("GozbaNaKlikApplication.Models.User", "User")
                        .WithOne("AdministratorProfile")
                        .HasForeignKey("GozbaNaKlikApplication.Models.AdministratorProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GozbaNaKlikApplication.Models.CourierProfile", b =>
                {
                    b.HasOne("GozbaNaKlikApplication.Models.User", "User")
                        .WithOne("CourierProfile")
                        .HasForeignKey("GozbaNaKlikApplication.Models.CourierProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GozbaNaKlikApplication.Models.CustomerProfile", b =>
                {
                    b.HasOne("GozbaNaKlikApplication.Models.User", "User")
                        .WithOne("CustomerProfile")
                        .HasForeignKey("GozbaNaKlikApplication.Models.CustomerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GozbaNaKlikApplication.Models.Meal", b =>
                {
                    b.HasOne("GozbaNaKlikApplication.Models.Restaurant", "Restaurant")
                        .WithMany("Meals")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("GozbaNaKlikApplication.Models.OwnerProfile", b =>
                {
                    b.HasOne("GozbaNaKlikApplication.Models.User", "User")
                        .WithOne("OwnerProfile")
                        .HasForeignKey("GozbaNaKlikApplication.Models.OwnerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GozbaNaKlikApplication.Models.Restaurant", b =>
                {
                    b.HasOne("GozbaNaKlikApplication.Models.OwnerProfile", "Owner")
                        .WithMany("MyRestaurants")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("GozbaNaKlikApplication.Models.CustomerProfile", b =>
                {
                    b.Navigation("CustomerAddresses");
                });

            modelBuilder.Entity("GozbaNaKlikApplication.Models.OwnerProfile", b =>
                {
                    b.Navigation("MyRestaurants");
                });

            modelBuilder.Entity("GozbaNaKlikApplication.Models.Restaurant", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("GozbaNaKlikApplication.Models.User", b =>
                {
                    b.Navigation("AdministratorProfile");

                    b.Navigation("CourierProfile");

                    b.Navigation("CustomerProfile");

                    b.Navigation("OwnerProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
